### PR TITLE
clipped square fixtures

### PR DESCRIPTION
**Pull request by mapsam**
Working on fixtures for #83 

- [x] exact tile boundary
- [x] one greater than extent
- [x] one less than extent
- [x] large buffer

cc @springmeyer

### CODE REVIEW

**Comment by mapsam** [comment]
One thing to confirm here is that the winding order is correct. I drew these clockwise (top left -> top right -> bottom right -> closepath) - is that proper?

**Comment by joto** [comment]
@mapsam I think the coordinates are wrong. With the extent 4096, the coordinates should go from 0 to 4095, not to 4096. So they are all off by one.

Also the descriptions are confusing. I am not a native speaker, but `minus one coordinate` etc. sounds wrong to me. Maybe `minus one unit`? Or `coordinate unit`?

**Comment by mapsam** [comment]
@joto great catch, I was starting at zero but counting from 1.

> Maybe minus one unit? Or coordinate unit?

Agree the phrasing isn't ideal. Thanks for suggesting other options! This is also why I included some ASCII art in the src files since that felt like a helpful visual addition.

**Comment by flippmoke** [comment]
>With the extent 4096, the coordinates should go from 0 to 4095, not to 4096

As per the spec:

```
For example, if a tile has an extent of 4096, coordinate units within the tile refer to 1/4096th of its square dimensions. A coordinate of 0 is on the top or left edge of the tile, and a coordinate of 4096 is on the bottom or right edge. Coordinates from 1 through 4095 inclusive are fully within the extent of the tile, and coordinates less than 0 or greater than 4096 are fully outside the extent of the tile. A point at (1,10) or (4095,10) is within the extent of the tile. A point at (0,10) or (4096,10) is on the edge of the extent. A point at (-1,10) or (4097,10) is outside the extent of the tile.
```

**Comment by mapsam** [comment]
Thanks @flippmoke - with that definition, I believe my numbers are correct (had to draw it on paper to confirm).

@joto I updated the language to be `unit` instead of `coordinate`!

**Pull request merged**
